function createPresetColors({
  background,
  surface,
  border,
  accent,
  accentDark,
  text,
  textMuted,
  secondary,
  panelBackground = surface,
  panelBorder = border,
  inputBackground = surface,
  inputBorder = border,
  inputText = text,
  inputPlaceholder = textMuted,
  buttonBackground = text,
  buttonHoverBackground = accentDark,
  buttonText = '#FFFFFF',
  success = '#3E6A45',
  error = '#B94747',
}) {
  return {
    primary: text,
    secondary,
    accent,
    accentDark,
    accentSecondary: accentDark,
    background,
    surface,
    border,
    text,
    textMuted,
    panelBackground,
    panelBorder,
    inputBackground,
    inputBorder,
    inputText,
    inputPlaceholder,
    buttonBackground,
    buttonHoverBackground,
    buttonText,
    success,
    error,
  };
}

export const FONT_OPTIONS = [
  { id: 'bellefair', label: 'Bellefair', labelHe: 'בלפייר', family: "'Bellefair', Georgia, serif", categoryHe: 'קלאסי', supports: ['en'], sampleEn: 'SweetLight' },
  { id: 'cormorant', label: 'Cormorant Garamond', labelHe: 'קורמורנט גרמונד', family: "'Cormorant Garamond', serif", categoryHe: 'עריכתי', supports: ['en'], sampleEn: 'Editorial Story' },
  { id: 'frank-ruhl', label: 'Frank Ruhl Libre', labelHe: 'פרנק ריהל ליברה', family: "'Frank Ruhl Libre', serif", categoryHe: 'סריפ עברי', supports: ['he', 'en'], sampleHe: 'הסיפור שלכם' },
  { id: 'heebo', label: 'Heebo', labelHe: 'היבו', family: "'Heebo', sans-serif", categoryHe: 'נקי', supports: ['he', 'en'], sampleHe: 'רגעים שנשארים' },
  { id: 'assistant', label: 'Assistant', labelHe: 'אסיסטנט', family: "'Assistant', sans-serif", categoryHe: 'מודרני', supports: ['he', 'en'], sampleHe: 'צילום שמרגיש טבעי' },
  { id: 'rubik', label: 'Rubik', labelHe: 'רוביק', family: "'Rubik', sans-serif", categoryHe: 'גאומטרי', supports: ['he', 'en'], sampleHe: 'היום המיוחד שלכם' },
  { id: 'secular-one', label: 'Secular One', labelHe: 'סקולר וואן', family: "'Secular One', sans-serif", categoryHe: 'כותרות', supports: ['he', 'en'], sampleHe: 'אהבה בפריים' },
  { id: 'great-vibes', label: 'Great Vibes', labelHe: 'גרייט וייבס', family: "'Great Vibes', cursive", categoryHe: 'כתב יד', supports: ['en'], sampleEn: 'Our Story', englishOnly: true },
];

export const ABOUT_LAYOUT_OPTIONS = [
  { id: 'single', label: 'תמונה יחידה', preview: 'preview-single' },
  { id: 'pair', label: 'זוג תמונות', preview: 'preview-pair' },
  { id: 'editorial', label: 'מערכתי', preview: 'preview-editorial' },
];

export const ABOUT_MASK_OPTIONS = [
  { id: 'soft-square', label: 'ריבוע רך', preview: 'preview-mask-soft' },
  { id: 'circle', label: 'עיגול', preview: 'preview-mask-circle' },
  { id: 'arch', label: 'קשת', preview: 'preview-mask-arch' },
  { id: 'organic', label: 'אורגני נע', preview: 'preview-mask-organic' },
];

export const ABOUT_CONTENT_POSITIONS = [
  { id: 'start', label: 'קלאסי', preview: 'preview-content-start' },
  { id: 'center', label: 'מרכזי', preview: 'preview-content-center' },
  { id: 'end', label: 'פתוח', preview: 'preview-content-end' },
];

export const ABOUT_STATS_LAYOUTS = [
  { id: 'row', label: 'שורה' },
  { id: 'grid', label: 'רשת' },
  { id: 'cards', label: 'כרטיסים' },
];

export const TEXT_TEMPLATES = [
  {
    id: 'classic-editorial',
    nameHe: 'קלאסי עריכתי',
    headingFamily: "'Bellefair', Georgia, serif",
    bodyFamily: "'Heebo', sans-serif",
    heroTitleFamily: "'Great Vibes', cursive",
  },
  {
    id: 'romantic-story',
    nameHe: 'רומנטי רך',
    headingFamily: "'Cormorant Garamond', serif",
    bodyFamily: "'Frank Ruhl Libre', serif",
    heroTitleFamily: "'Great Vibes', cursive",
  },
  {
    id: 'modern-clean',
    nameHe: 'מודרני נקי',
    headingFamily: "'Secular One', sans-serif",
    bodyFamily: "'Assistant', sans-serif",
    heroTitleFamily: "'Bellefair', Georgia, serif",
  },
  {
    id: 'soft-luxury',
    nameHe: 'יוקרתי עדין',
    headingFamily: "'Frank Ruhl Libre', serif",
    bodyFamily: "'Heebo', sans-serif",
    heroTitleFamily: "'Cormorant Garamond', serif",
  },
  {
    id: 'minimal-gallery',
    nameHe: 'גלריה מינימליסטית',
    headingFamily: "'Rubik', sans-serif",
    bodyFamily: "'Assistant', sans-serif",
    heroTitleFamily: "'Bellefair', Georgia, serif",
  },
];

export const COLOR_PRESETS = [
  {
    id: 'sand-gold',
    nameHe: 'חול וזהב',
    swatch: ['#FAFAF8', '#C9A96E'],
    colors: createPresetColors({
      background: '#FAFAF8',
      surface: '#F4F1EC',
      border: '#E0D9CE',
      accent: '#C9A96E',
      accentDark: '#A8834A',
      text: '#1A1814',
      textMuted: '#7A7570',
      secondary: '#4E4A46',
      panelBackground: '#FCF9F4',
      inputBackground: '#FFFFFF',
      inputBorder: '#D7CCBA',
    }),
  },
  {
    id: 'deep-dark',
    nameHe: 'כהה עמוק',
    swatch: ['#111111', '#D4A843'],
    colors: createPresetColors({
      background: '#111111',
      surface: '#1A1A1A',
      border: '#343434',
      accent: '#D4A843',
      accentDark: '#B88A2A',
      text: '#F2EFE8',
      textMuted: '#AEA79E',
      secondary: '#D8D2C8',
      panelBackground: '#171717',
      panelBorder: '#3B3B3B',
      inputBackground: '#202020',
      inputBorder: '#5A5248',
      inputText: '#FFF8ED',
      inputPlaceholder: '#BBB2A5',
      buttonBackground: '#D4A843',
      buttonHoverBackground: '#E3BC64',
      buttonText: '#18120A',
      success: '#7FC985',
      error: '#F08B7A',
    }),
  },
  {
    id: 'pure-white',
    nameHe: 'לבן נקי',
    swatch: ['#FFFFFF', '#2A2A2A'],
    colors: createPresetColors({
      background: '#FFFFFF',
      surface: '#F5F5F5',
      border: '#E4E4E4',
      accent: '#2A2A2A',
      accentDark: '#000000',
      text: '#1A1A1A',
      textMuted: '#888888',
      secondary: '#555555',
      panelBackground: '#FAFAFA',
      inputBackground: '#FFFFFF',
      inputBorder: '#D9D9D9',
    }),
  },
  {
    id: 'rose-blush',
    nameHe: 'ורוד עדין',
    swatch: ['#FBF5F2', '#B8705A'],
    colors: createPresetColors({
      background: '#FBF5F2',
      surface: '#F4E8E1',
      border: '#E6D0C5',
      accent: '#B8705A',
      accentDark: '#96503C',
      text: '#281610',
      textMuted: '#8A6860',
      secondary: '#5E3A30',
      panelBackground: '#FFF9F6',
      inputBackground: '#FFFDFC',
      inputBorder: '#D9B5A8',
    }),
  },
  {
    id: 'slate-silver',
    nameHe: 'אפור כסף',
    swatch: ['#F4F6F8', '#4A7A9B'],
    colors: createPresetColors({
      background: '#F4F6F8',
      surface: '#E8EDF1',
      border: '#D0D8DF',
      accent: '#4A7A9B',
      accentDark: '#326080',
      text: '#141E26',
      textMuted: '#647580',
      secondary: '#384856',
      panelBackground: '#FBFDFF',
      inputBackground: '#FFFFFF',
      inputBorder: '#B6C6D2',
    }),
  },
  {
    id: 'olive-sage',
    nameHe: 'זית מרווה',
    swatch: ['#F5F4EE', '#7A8762'],
    colors: createPresetColors({
      background: '#F5F4EE',
      surface: '#ECE9DE',
      border: '#D8D2C0',
      accent: '#7A8762',
      accentDark: '#5D684A',
      text: '#1F241A',
      textMuted: '#6A6F63',
      secondary: '#4B5143',
      panelBackground: '#FAF9F4',
      inputBackground: '#FFFFFF',
      inputBorder: '#C5C0AE',
    }),
  },
  {
    id: 'midnight-plum',
    nameHe: 'שזיף לילי',
    swatch: ['#F8F4F8', '#7E5C74'],
    colors: createPresetColors({
      background: '#F8F4F8',
      surface: '#F0E7EF',
      border: '#DCCFD8',
      accent: '#7E5C74',
      accentDark: '#5F4257',
      text: '#251A23',
      textMuted: '#74656F',
      secondary: '#4A3946',
      panelBackground: '#FEFAFD',
      inputBackground: '#FFFFFF',
      inputBorder: '#CDB9C7',
    }),
  },
  {
    id: 'seafoam-stone',
    nameHe: 'ירקרק אבן',
    swatch: ['#F3F7F6', '#5C8D86'],
    colors: createPresetColors({
      background: '#F3F7F6',
      surface: '#E7EFED',
      border: '#CADAD6',
      accent: '#5C8D86',
      accentDark: '#3F6D67',
      text: '#172220',
      textMuted: '#60716E',
      secondary: '#37514D',
      panelBackground: '#FBFEFD',
      inputBackground: '#FFFFFF',
      inputBorder: '#B6CEC9',
    }),
  },
  {
    id: 'terracotta-cream',
    nameHe: 'טרה קוטה',
    swatch: ['#FBF6F1', '#C96F4E'],
    colors: createPresetColors({
      background: '#FBF6F1',
      surface: '#F4E9DF',
      border: '#E2CCBC',
      accent: '#C96F4E',
      accentDark: '#A64F32',
      text: '#2B1C17',
      textMuted: '#876A5E',
      secondary: '#5B4038',
      panelBackground: '#FFF9F5',
      inputBackground: '#FFFFFF',
      inputBorder: '#DAB29D',
    }),
  },
  {
    id: 'ink-champagne',
    nameHe: 'דיו ושמפניה',
    swatch: ['#FAF8F1', '#B69A55'],
    colors: createPresetColors({
      background: '#FAF8F1',
      surface: '#F1ECDE',
      border: '#DED3BD',
      accent: '#B69A55',
      accentDark: '#8D7438',
      text: '#1B1B1F',
      textMuted: '#6F6D67',
      secondary: '#45454B',
      panelBackground: '#FFFDF7',
      inputBackground: '#FFFFFF',
      inputBorder: '#D4C4A0',
    }),
  },
  {
    id: 'noir-bronze',
    nameHe: 'נואר וברונזה',
    swatch: ['#0D0F12', '#C69A5A'],
    colors: createPresetColors({
      background: '#0D0F12',
      surface: '#151920',
      border: '#303640',
      accent: '#C69A5A',
      accentDark: '#9E7540',
      text: '#F5F1E8',
      textMuted: '#A7ACB4',
      secondary: '#DDE2E8',
      panelBackground: '#141820',
      panelBorder: '#39414D',
      inputBackground: '#1C222D',
      inputBorder: '#59616E',
      inputText: '#FDF8F0',
      inputPlaceholder: '#B7BDC7',
      buttonBackground: '#C69A5A',
      buttonHoverBackground: '#DDB270',
      buttonText: '#14100A',
      success: '#7ECB9C',
      error: '#F19784',
    }),
  },
  {
    id: 'forest-noir',
    nameHe: 'יער לילי',
    swatch: ['#101411', '#B8A36A'],
    colors: createPresetColors({
      background: '#101411',
      surface: '#182018',
      border: '#314034',
      accent: '#B8A36A',
      accentDark: '#8D7948',
      text: '#F2F0E7',
      textMuted: '#9DA599',
      secondary: '#D1D7CD',
      panelBackground: '#182119',
      panelBorder: '#3C4A3F',
      inputBackground: '#212B22',
      inputBorder: '#5A675C',
      inputText: '#FAF7F1',
      inputPlaceholder: '#B9C1B5',
      buttonBackground: '#B8A36A',
      buttonHoverBackground: '#CEB77C',
      buttonText: '#17130B',
      success: '#84C98A',
      error: '#F28981',
    }),
  },
  {
    id: 'velvet-wine',
    nameHe: 'יין קטיפתי',
    swatch: ['#140F13', '#D29A82'],
    colors: createPresetColors({
      background: '#140F13',
      surface: '#1E161D',
      border: '#3B2D38',
      accent: '#D29A82',
      accentDark: '#B56B52',
      text: '#F6ECE8',
      textMuted: '#B09AA4',
      secondary: '#E0D2CF',
      panelBackground: '#20171F',
      panelBorder: '#493744',
      inputBackground: '#2A1E28',
      inputBorder: '#6B5163',
      inputText: '#FFF5F1',
      inputPlaceholder: '#C2AFB7',
      buttonBackground: '#D29A82',
      buttonHoverBackground: '#E6B29A',
      buttonText: '#23130F',
      success: '#87C59B',
      error: '#F28B7E',
    }),
  },
  {
    id: 'cobalt-night',
    nameHe: 'קובלט לילי',
    swatch: ['#0D1320', '#D4A843'],
    colors: createPresetColors({
      background: '#0D1320',
      surface: '#162033',
      border: '#31425B',
      accent: '#D4A843',
      accentDark: '#A7812F',
      text: '#F5F7FB',
      textMuted: '#99A7BE',
      secondary: '#D6DFEE',
      panelBackground: '#162032',
      panelBorder: '#3B4E68',
      inputBackground: '#1F2B40',
      inputBorder: '#5B6E89',
      inputText: '#FFFFFF',
      inputPlaceholder: '#B9C5D7',
      buttonBackground: '#D4A843',
      buttonHoverBackground: '#E1BA63',
      buttonText: '#181208',
      success: '#81C6A2',
      error: '#F18F7B',
    }),
  },
  {
    id: 'espresso-ivory',
    nameHe: 'אספרסו ושנהב',
    swatch: ['#19130F', '#C98E5B'],
    colors: createPresetColors({
      background: '#19130F',
      surface: '#241C17',
      border: '#45342A',
      accent: '#C98E5B',
      accentDark: '#A56534',
      text: '#F8F2EC',
      textMuted: '#B8A79B',
      secondary: '#E2D7CE',
      panelBackground: '#251D18',
      panelBorder: '#533D31',
      inputBackground: '#302620',
      inputBorder: '#6C5548',
      inputText: '#FFF7F0',
      inputPlaceholder: '#C7B6A8',
      buttonBackground: '#C98E5B',
      buttonHoverBackground: '#DEAA78',
      buttonText: '#21160F',
      success: '#8BC493',
      error: '#F19276',
    }),
  },
  {
    id: 'emerald-studio',
    nameHe: 'סטודיו אמרלד',
    swatch: ['#0E1715', '#B7A16C'],
    colors: createPresetColors({
      background: '#0E1715',
      surface: '#162320',
      border: '#2E4741',
      accent: '#B7A16C',
      accentDark: '#8C7A4F',
      text: '#F2F3EE',
      textMuted: '#97A6A1',
      secondary: '#D4D9D4',
      panelBackground: '#182522',
      panelBorder: '#3B5750',
      inputBackground: '#20302C',
      inputBorder: '#5A726C',
      inputText: '#FBFDF8',
      inputPlaceholder: '#BCC7C4',
      buttonBackground: '#B7A16C',
      buttonHoverBackground: '#CBB885',
      buttonText: '#17140D',
      success: '#89C99C',
      error: '#F09181',
    }),
  },
  {
    id: 'linen-charcoal',
    nameHe: 'פשתן ופחם',
    swatch: ['#F8F5F0', '#5D6778'],
    colors: createPresetColors({
      background: '#F8F5F0',
      surface: '#EEE8DE',
      border: '#D8CCBC',
      accent: '#5D6778',
      accentDark: '#454D5C',
      text: '#1F1B18',
      textMuted: '#7B736A',
      secondary: '#4A474F',
      panelBackground: '#FFFDF9',
      inputBackground: '#FFFFFF',
      inputBorder: '#C9BEAF',
    }),
  },
  {
    id: 'apricot-smoke',
    nameHe: 'אפרסק ומעושן',
    swatch: ['#FFF6EF', '#B36E52'],
    colors: createPresetColors({
      background: '#FFF6EF',
      surface: '#F6E8DC',
      border: '#E6CDBB',
      accent: '#B36E52',
      accentDark: '#8E5038',
      text: '#2A1A15',
      textMuted: '#8C6F63',
      secondary: '#5D433A',
      panelBackground: '#FFFBF7',
      inputBackground: '#FFFFFF',
      inputBorder: '#D8B49F',
    }),
  },
  {
    id: 'dusty-lilac',
    nameHe: 'לילך מעושן',
    swatch: ['#FBF8FD', '#7C6A92'],
    colors: createPresetColors({
      background: '#FBF8FD',
      surface: '#F1EAF6',
      border: '#D6C9E0',
      accent: '#7C6A92',
      accentDark: '#5E4F73',
      text: '#241C2A',
      textMuted: '#766B82',
      secondary: '#4D4357',
      panelBackground: '#FEFCFF',
      inputBackground: '#FFFFFF',
      inputBorder: '#C6B7D3',
    }),
  },
  {
    id: 'nordic-fjord',
    nameHe: 'פיורד נורדי',
    swatch: ['#F3F8FA', '#547C8D'],
    colors: createPresetColors({
      background: '#F3F8FA',
      surface: '#E7EFF2',
      border: '#C9D7DE',
      accent: '#547C8D',
      accentDark: '#3A5E6E',
      text: '#18242B',
      textMuted: '#687B84',
      secondary: '#40545E',
      panelBackground: '#FBFEFF',
      inputBackground: '#FFFFFF',
      inputBorder: '#B9CBD4',
    }),
  },
  {
    id: 'charcoal-rose',
    nameHe: 'פחם ורוזה',
    swatch: ['#121315', '#D2A3A7'],
    colors: createPresetColors({
      background: '#121315',
      surface: '#1A1D22',
      border: '#353B44',
      accent: '#D2A3A7',
      accentDark: '#B07A80',
      text: '#F5EFF1',
      textMuted: '#A8A1AA',
      secondary: '#DAD3D8',
      panelBackground: '#1B1E24',
      panelBorder: '#434955',
      inputBackground: '#232832',
      inputBorder: '#626875',
      inputText: '#FFF8FA',
      inputPlaceholder: '#BEB7C1',
      buttonBackground: '#D2A3A7',
      buttonHoverBackground: '#E1B8BC',
      buttonText: '#201215',
      success: '#84C59F',
      error: '#F19186',
    }),
  },
  {
    id: 'storm-blue',
    nameHe: 'סערה כחולה',
    swatch: ['#EAF1F7', '#456D9C'],
    colors: createPresetColors({
      background: '#EAF1F7',
      surface: '#DEE8F1',
      border: '#C1CFDE',
      accent: '#456D9C',
      accentDark: '#2F527A',
      text: '#16202C',
      textMuted: '#66798A',
      secondary: '#3E5264',
      panelBackground: '#F7FBFF',
      inputBackground: '#FFFFFF',
      inputBorder: '#ADC0D3',
    }),
  },
  {
    id: 'cedar-ivory',
    nameHe: 'ארז ושנהב',
    swatch: ['#FBF8F2', '#8C6A4E'],
    colors: createPresetColors({
      background: '#FBF8F2',
      surface: '#F0E8DD',
      border: '#DCCDBC',
      accent: '#8C6A4E',
      accentDark: '#6B4E37',
      text: '#211A15',
      textMuted: '#7E7066',
      secondary: '#4D4139',
      panelBackground: '#FFFDF9',
      inputBackground: '#FFFFFF',
      inputBorder: '#CAB8A5',
    }),
  },
  {
    id: 'copper-night',
    nameHe: 'ליל נחושת',
    swatch: ['#15110F', '#C27A56'],
    colors: createPresetColors({
      background: '#15110F',
      surface: '#1F1815',
      border: '#3A2E28',
      accent: '#C27A56',
      accentDark: '#9A5635',
      text: '#F8F0E8',
      textMuted: '#B9A89A',
      secondary: '#DED0C4',
      panelBackground: '#211916',
      panelBorder: '#4A3930',
      inputBackground: '#2A211D',
      inputBorder: '#685247',
      inputText: '#FFF7F1',
      inputPlaceholder: '#C8B6A9',
      buttonBackground: '#C27A56',
      buttonHoverBackground: '#D89471',
      buttonText: '#21140D',
      success: '#8CC79A',
      error: '#F2937C',
    }),
  },
];

export const LOGO_FRAME_OPTIONS = [
  { id: 'none', label: 'ללא מסגרת' },
  { id: 'transparent-ring', label: 'עיגול שקוף' },
  { id: 'transparent-ring-shadow', label: 'עיגול שקוף עם הצללה' },
  { id: 'white-disc', label: 'עיגול לבן' },
  { id: 'white-disc-shadow', label: 'עיגול לבן עם הצללה' },
];

export function getTextTemplateById(id) {
  return TEXT_TEMPLATES.find((template) => template.id === id) || TEXT_TEMPLATES[0];
}

export function getColorPresetById(id) {
  return COLOR_PRESETS.find((preset) => preset.id === id) || COLOR_PRESETS[0];
}

export function getFontFamilyById(id, fallback = FONT_OPTIONS[0].family) {
  return FONT_OPTIONS.find((font) => font.id === id)?.family || fallback;
}
